services:
  - type: web
    name: spring-boot-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildCommand: ./mvnw package
    startCommand: java -jar target/spring-boot-0.0.1-SNAPSHOT.jar
